### create an artic;e
POST http://localhost:5000/author-api/article
Content-Type: application/json

{
    "author":"69b44e3b187ff8b17c15beb5",
    "title":"Article demo by demo",
    "category":"Demo",
    "content":"test article for demo"
}

### add a new aauhtor i.e. REGISTRATION
POST http://localhost:5000/auth/users
Content-Type: application/json

{
    "firstName":"A",
    "lastName":"author2",
    "email":"author2@gmail.com",
    "password":"author2",
    "role":"AUTHOR",
    "profileImageUrl":"xdcfvgbhnjm"
}
###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"author1@gmail.com",
    "password":"author1"
}



### get own articles
GET http://localhost:5000/author-api/articles

### update own article 
PUT http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b4fc6571a8246fe6c0a63d",
    "title":"This is modified aticle of author 2",
    "category":"programming",
    "content":"fvgbhnj"
}

### delete own article
PATCH http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b4ec68b332bd77842f3abd",
    "isArticleActive":false
}