### add a new user i.e. REGISTRATION
POST http://localhost:5000/auth/users
Content-Type: application/json

{
    "firstName":"A",
    "lastName":"author1",
    "email":"author1@gmail.com",
    "password":"author1",
    "role":"AUTHOR",
    "profileImageUrl":"xdcfvgbhnjm"
}

### login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"author1@gmail.com",
    "password":"author1"
}

###
GET  http://localhost:5000/auth/logout

### read articles of all authors
GET http://localhost:5000/user-api/articles


### add comment by user to an article
PUT http://localhost:5000/user-api/articles
Content-Type: application/json

{
    "articleId":"",
    "comment":""
}